#
# Jenkins pipeline for CNaaS
#

disabled: false

slack:
  room: "cnaas-builds"

git:
  branch: develop
builders:
  - docker
pre_build_script:
  - cp docker/front/Dockerfile .
docker_name: cnaas/front
docker_context_dir: .
docker_tags:
  - "v1.9.0"
  - "v1.9"

extra_jobs:
  - name: cnaas-front-master
    git:
      branch: master
    builders:
      - docker
    pre_build_script:
      - cp docker/front/Dockerfile .
    docker_name: cnaas/front
    docker_context_dir: .
    docker_skip_tag_as_latest: false
    docker_tags:
      - "v1.8.1"
      - "v1.8"
