import PropTypes from "prop-types";
import { useMemo, useState } from "react";
import { Popup, Icon } from "semantic-ui-react";
import VerifyDiffInfo from "./VerifyDiffInfo";
import VerifyDiffResult from "./VerifyDiffResult";

VerifyDiff.propTypes = {
  devices: PropTypes.object,
  dryRunChangeScore: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};

function VerifyDiff({ devices, dryRunChangeScore }) {
  const [expanded, setExpanded] = useState(true);

  const deviceNames = useMemo(() => Object.keys(devices), [devices]);
  const deviceData = useMemo(() => Object.values(devices), [devices]);

  return (
    <section className="task-container">
      <header className="heading">
        <h2>
          <Icon
            name="dropdown"
            onClick={() => setExpanded((prev) => !prev)}
            rotated={expanded ? null : "counterclockwise"}
          />
          Verify difference (3/4)
          <Popup
            content="Shows diffs generated by the device operating system. Make sure nothing unexpected has changed."
            trigger={<Icon name="question circle outline" size="small" />}
            wide
          />
        </h2>
      </header>
      <div className="task-collapsable" hidden={!expanded}>
        <p>Step 3 of 4: Look through and verify diff</p>
        <div>
          <VerifyDiffInfo
            deviceNames={deviceNames}
            dryRunChangeScore={dryRunChangeScore}
          />
          <VerifyDiffResult deviceNames={deviceNames} deviceData={deviceData} />
        </div>
      </div>
    </section>
  );
}

export default VerifyDiff;
