import { useMemo } from "react";
import { Tooltip } from "../../../../components/Tooltip";
import HelpOutlineOutlinedIcon from "@mui/icons-material/HelpOutlineOutlined";
import { Task } from "../../../../components/Task";
import { VerifyDiffInfo } from "./VerifyDiffInfo";
import {
  VerifyDiffResult,
  type DeviceJobTaskDiff,
} from "../../../../components/VerifyDiffResult";
import type { DevicesJobResult } from "../../../../types/job";

type VerifyDiffProps = {
  readonly devices: DevicesJobResult["devices"];
  readonly dryRunChangeScore: number | null;
};

export function VerifyDiff({ devices, dryRunChangeScore }: VerifyDiffProps) {
  const deviceList: DeviceJobTaskDiff[] = useMemo(
    () =>
      Object.entries(devices).map(([name, { job_tasks: jobTasks }]) => ({
        name,
        jobTasks,
      })),
    [devices],
  );

  return (
    <Task
      title={
        <>
          Verify difference (3/4)
          <Tooltip title="Shows diffs generated by the device operating system. Make sure nothing unexpected has changed.">
            <HelpOutlineOutlinedIcon fontSize="small" />
          </Tooltip>
        </>
      }
    >
      <p>Step 3 of 4: Look through and verify diff</p>
      <div>
        <VerifyDiffInfo
          deviceNames={deviceList.map((d) => d.name)}
          dryRunChangeScore={dryRunChangeScore}
        />
        <VerifyDiffResult devices={deviceList} />
      </div>
    </Task>
  );
}
