import { useMemo, useState } from "react";
import { Tooltip } from "../../../../components/Tooltip";
import HelpOutlineOutlinedIcon from "@mui/icons-material/HelpOutlineOutlined";
import ArrowDropDownIcon from "@mui/icons-material/ArrowDropDown";
import { VerifyDiffInfo } from "./VerifyDiffInfo";
import {
  VerifyDiffResult,
  type DeviceJobTaskDiff,
} from "../../../../components/VerifyDiffResult";
import type { DevicesJobResult } from "../../../../types/job";

type VerifyDiffProps = {
  readonly devices: DevicesJobResult["devices"];
  readonly dryRunChangeScore: number | null;
};

export function VerifyDiff({ devices, dryRunChangeScore }: VerifyDiffProps) {
  const [expanded, setExpanded] = useState(true);

  const deviceList: DeviceJobTaskDiff[] = useMemo(
    () =>
      Object.entries(devices).map(([name, { job_tasks: jobTasks }]) => ({
        name,
        jobTasks,
      })),
    [devices],
  );

  return (
    <section className="task-container">
      <header className="heading">
        <h2>
          <ArrowDropDownIcon
            onClick={() => setExpanded((prev) => !prev)}
            sx={{
              cursor: "pointer",
              transform: expanded ? undefined : "rotate(-90deg)",
            }}
          />
          Verify difference (3/4)
          <Tooltip title="Shows diffs generated by the device operating system. Make sure nothing unexpected has changed.">
            <HelpOutlineOutlinedIcon fontSize="small" />
          </Tooltip>
        </h2>
      </header>
      <div className="task-collapsable" hidden={!expanded}>
        <p>Step 3 of 4: Look through and verify diff</p>
        <div>
          <VerifyDiffInfo
            deviceNames={deviceList.map((d) => d.name)}
            dryRunChangeScore={dryRunChangeScore}
          />
          <VerifyDiffResult devices={deviceList} />
        </div>
      </div>
    </section>
  );
}
